Resource bundle support
Leanplum/Leanplum-iOS-SDK pull request #412
Opened 2020-11-12 09:29 UTC by dejan2k

2020-11-12 09:30 UTC, dejan2k commented
It's marked as a draft because it is not thoroughly tested yet

2020-11-12 10:31 UTC, milos1290 requested changes

2020-11-12 10:31 UTC, milos1290 commented on Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPInterstitialViewController.m
> +    NSURL *bundleUrl = [bundle URLForResource:@"Leanplum-iOS-SDK" withExtension:@".bundle"];
We can probably move getting of bundle to Utils class so its not repeated.

2020-11-17 08:35 UTC, nzagorchev approved these changes

2020-11-18 10:24 UTC, merged