[SDK-446] onRunActionNamed
Leanplum/Leanplum-iOS-SDK pull request #441
Opened 2021-06-16 12:32 UTC by nzagorchev

What              | Where/Who
------------------|----------------------------------------
JIRA Issue        | [SDK-446](https://leanplum.atlassian.net/browse/SDK-446)

Example Usage:
```
    [Leanplum onAction:@"Center Popup" invoke:^BOOL(LPActionContext * _Nonnull context) {
        [context onRunActionNamed:^BOOL(LPActionContext * _Nonnull context) {
            NSString *an = [context actionName]; // Accept action
            return NO;
        }];
        return YES;
    }];
```

## Background
Enable callbacks when in-app message actions are run. For example, Accept action or Select button 1 action.

## Implementation
Add `onRunActionNamed` method to register blocks for action run callbacks. The callbacks reuse the `LeanplumActionBlock`.

This PR also refactors imports of Action Context (previously silently done through Leanplum header import). Aims to prevent circular references.

## Testing steps
Tests onRunActionNamed block execution and onAction.

## Is this change backwards-compatible?

2021-06-22 18:13 UTC, dejan2k approved these changes

2021-06-28 10:29 UTC, milos1290 requested changes

2021-06-28 10:47 UTC, milos1290 approved these changes

2021-06-28 14:23 UTC, dejan2k approved these changes

2021-06-29 11:31 UTC, merged

2021-07-07 13:46 UTC, tthbalazs commented on Leanplum-SDK/Classes/Leanplum.h
> -#import "LPActionContext.h"
This change actually breaks the SDK when you include it via Swift Package Manager. The `LPActionContext` class is no longer available.