Configurable API endpoint
Leanplum/Leanplum-iOS-SDK pull request #488
Opened 2022-03-01 08:22 UTC by nzagorchev

What              | Where/Who
------------------|----------------------------------------
JIRA Issue        | [SDK-661](https://leanplum.atlassian.net/browse/SDK-661)
People Involved   | @nzagorchev 

## Background
Change API and Dev server endpoints on the fly, based on API response. Response example in `change_host_response.json`. HTTP status will be 200 OK.
In that case, the SDK must retry the request to the new endpoint.

## Implementation
`LPRequestSender` checks if the response returns a new API config, then changes the hosts and retries the request. Callbacks will be executed by the subsequent request.

`LeanplumSocket` is modified, so a new engine can be created and connected with. Changes were required in Socket_IO and WebSocket classes to deallocate objects correctly.
Disconnecting and Connecting again (all async) proved to be inefficient.

_Note:_ `sendNow` for request with datas does _not_ update the API config. Such a request is _only_ sent when uploading app icons.

As part of this PR, the following changes are also made:
- Rewriting the `LPAPIConfig` and separating from `LPConstants`
- Moving user data to User class
- Renaming servlet to path
- Moving Request UUID to Swift

## Testing steps
Manual and Unit tests.

## Is this change backwards-compatible?
Yes

2022-03-03 14:03 UTC, milos1290 requested changes

2022-03-03 14:03 UTC, milos1290 commented on LeanplumSDK/LeanplumSDK/ClassesSwift/User.swift
> +
remove empty line

2022-03-03 14:03 UTC, milos1290 commented on LeanplumSDK/LeanplumSDK/ClassesSwift/User.swift
> +    public struct UserKey {
Move to the top of the class

2022-03-03 14:03 UTC, milos1290 commented on LeanplumSDK/LeanplumSDK/ClassesSwift/Utilities/WeakTimer.swift
> +
remove empty line

2022-03-03 14:03 UTC, milos1290 commented on LeanplumSDK/LeanplumSDK/ClassesSwift/Utilities/WeakTimer.swift
> +        return Timer.scheduledTimer(timeInterval: timeInterval,
```
  return .scheduledTimer(timeInterval: timeInterval,
                                    target: target,
                                    selector: #selector(fire),
                                    userInfo: userInfo,
                                    repeats: repeats)
```

2022-03-07 10:08 UTC, nzagorchev commented on LeanplumSDK/LeanplumSDK/ClassesSwift/ApiConfig.swift
> +    enum Constants {
Moving to top for now, we can restructure the constants in Dejans PR later on

2022-03-07 12:53 UTC, nzagorchev commented on LeanplumSDK/LeanplumSDK/Classes/Managers/Networking/LPRequestSender.m
> +    if ([json isKindOfClass:NSDictionary.class]) {
yes, the response should be 200 but with success:false and contain the config. 
The response of the multi is always an array. In this case, it should return only one object with new endpoints but we iterate to be safe.

2022-03-07 16:25 UTC, hborisoff approved these changes
Looks good

2022-03-08 10:02 UTC, milos1290 approved these changes

2022-03-08 10:18 UTC, merged